### ISSUE TITLE
Provide variable fields from ClusterClass

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/cluster-gen#3]
To make use of all possible variables provided by the specific ClusterClass, this should be generated out of it, the same way we do for the documentation, see https://github.com/SovereignCloudStack/cluster-stacks/pull/94.
In case of moin cluster, they are available publicly available [here](https://moin.k8s.scs.community/apis/cluster.x-k8s.io/v1beta1/clusterclasses)

**Comment by mxmxchere** [comment]
Not only the variables can be fetched from the apiserver-link. The available cluster-classes and the namespaces they are deployed in can be used as input too.

**Comment by eigenpaul** [comment]
The new dynamic approach fetches all available ClusterClass definitions from the kubeapi-server of the moin-cluster via the REST API provided by [capi-jsgen](https://github.com/SovereignCloudStack/capi-jsgen). The response is a [JSON Schema](https://json-schema.org/) object, which gets read by [react-jsonschema-form](https://rjsf-team.github.io/react-jsonschema-form/) to render the form. This new library allows us to dynamically render forms by providing a schema of the data and the associated UI components
